name: Dispatch OpenAPI Schema Update
on:
  push:
    branches: [main]
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: technote-space/get-diff-action@v4.0.1
        with:
          PATTERNS: doc/openapi.yml

      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source_file: "doc/openapi.yml"
          destination_repo: "flt3150sk/auto-merge-test"
          destination_folder: ""
          destination_branch: "main"
          user_email: "muranaka.kouske@gmail.com"
          user_name: "flt3150sk"
          commit_message: "updated openapi"

      - name: Dispatch update-openapi
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: flt3150sk/auto-merge-test
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: update-openapi
