name: Dispatch OpenAPI Schema Update
on:
  push:
    branches: [main]
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create new branch in destination repository
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_SECRET }}
        with:
          branch: 'feature/update-openapi'
          repository: 'flt3150sk/auto-merge-test'

      - uses: technote-space/get-diff-action@v4.0.1
        with:
          PATTERNS: doc/openapi.yml

      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ORG_SECRET }}
        with:
          source_file: "doc/openapi.yml"
          destination_repo: "flt3150sk/auto-merge-test"
          destination_folder: ""
          destination_branch: "feature/update-openapi"
          user_email: "hoge@gmail.com"
          user_name: "hoge"
          commit_message: "updated openapi"

      - name: Dispatch update-openapi
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: flt3150sk/auto-merge-test
          token: ${{ secrets.ORG_SECRET }}
          event-type: update-openapi
